### ISSUE TITLE
Improve message title/content

### ISSUE THREAD

**Issue by DL6ER** [yubiuser/docker-event-monitor#33]
These are the messages I'm referring to in the remainder of this issue ticket:
![Screenshot from 2023-09-23 10-16-33](https://github.com/yubiuser/docker-event-monitor/assets/16748619/895b4b1f-e168-4690-84e1-baf86f29fef5)

The first message I ever received contained a timestamp string, nothing else. The title was helpful:

![Screenshot from 2023-09-23 10-16-44](https://github.com/yubiuser/docker-event-monitor/assets/16748619/fd6b10b6-5dab-4ddc-9022-7b1893ef63e6)

The following messages did not contain a useful title, but what happened was now in the content of the mail:

![Screenshot from 2023-09-23 10-16-50](https://github.com/yubiuser/docker-event-monitor/assets/16748619/fc13ee88-bdd2-4e5b-afe0-c778872f745a)
![Screenshot from 2023-09-23 10-16-54](https://github.com/yubiuser/docker-event-monitor/assets/16748619/688f8e15-7979-4435-9852-773faf1df754)

My suggestions at this point would be to 

1. Improve the status message to something like
   ```
   Docker event monitor was started at XX-XX-2023 XX:YY:ZZ
   ```
   (or similar)
2. Change the header from the generic ~~New Docker Event~~ to something dynamic like `Container postgres:14: stop`. For brevity, you could even skip the leading "Container" and use the title/subject `postgres:14: stop` and, subsequently, `postgres:14: start`

I am aware that my suggestion is based on the e-mail reporting where a sender will always be visible allowing to identify the origin immediately. I am not using any of the other notification method your monitor offers, so I cannot speak for them if the same change would be useful over there as well.

**Comment by yubiuser** [comment]
Thanks for your tests and suggestions. There is certainly room for improvement here. It's a bit tricky because I tried to keep the messages very general, because users are free to choose which events they want to subscribe to. That's why I have this leading `Object  Container` (some might subscribe to `images` or `networks`). Depending on the used reporter, space in the 'titel' is also more constrained than in an E-Mail.

**Comment by DL6ER** [comment]
This is addressed in #40
