### ISSUE TITLE
Improve docker-compose support

### ISSUE THREAD

**Issue by DL6ER** [yubiuser/docker-event-monitor#34]
## What is the problem?
I heavily use `docker compose` to provide individual services on my servers. When `docker-event-monitor` sends me a message like
> ```
> Object 'Container' with ID 2a51bd18 from image postgres:14 reported: stop
> ```

it is difficult to know which container was actually affected because years after I have set up my `gitea`, I might simply have forgotten that `postgres` is used here. Another possibility would be that it could be used more than once, e.g., when using several provided `docker-compose.yml` files from various resources on the web.

## Background
The structure of my services (all managed using `docker compose`) is pretty common, like
```
/home/<user>/docker
/home/<user>/docker/gittea
/home/<user>/docker/gittea/docker-compose.yml
/home/<user>/docker/proxy
/home/<user>/docker/proxy/docker-compose.yml
/home/<user>/docker/bbb
/home/<user>/docker/bbb/docker-compose.yml
/home/<user>/docker/mailserver
/home/<user>/docker/mailserver/docker-compose.yml
/home/<user>/docker/watchtower
/home/<user>/docker/watchtower/docker-compose.yml
... (several more)
```

(yes, they are intentionally not running as `root`)

## My suggestion
Include details about the `docker compose` context if applicable. The information should be available through the docker events, e.g.:
> ```
> 2023-09-23T10:29:15.081683269+02:00 container restart 2a51bd189e885381c80d63c8f6d7906a5f220f93412beb9b6eb96e9dfdd2efc4 (com.docker.compose.config-hash=20d8294d54fe37f3c8f4395ba8db4770df004b762180be24af6dcad170c4396c, com.docker.compose.container-number=1, com.docker.compose.depends_on=, com.docker.compose.image=sha256:4d8f13d97fae84ee0f5e9231b89a7957839a8de3ff49b7faab1feac5cab01b6c, com.docker.compose.oneoff=False, com.docker.compose.project=gitea, com.docker.compose.project.config_files=/home/<user>/docker/gitea/docker-compose.yml, com.docker.compose.project.working_dir=/home/<user>/docker/gitea, com.docker.compose.replace=7166e98e5db5339990b54505dd3a62e9b179b53cf0b0a16b0771639aef2ce247, com.docker.compose.service=db, com.docker.compose.version=2.20.2, image=postgres:14, name=gitea-db-1)
> ```

Specifically:
- `name=gitea-db-1`
- `com.docker.compose.project=gitea`
- `com.docker.compose.service=db`
- `com.docker.compose.project.working_dir=/home/<user>/docker/gitea`

To a human consuming the messages generated by `docker-event-monitor`, `name` may also be a more obvious choice than the currently printed container ID.

## Example message
With `docker compose` context:

From: ...
Subject: `gitea-db-1 container restart`
Content: `Container gitea-db-1 (gitea:db defined in /home/<user>/docker/gitea) was restarted`

Without `docker compose`:

From: ...
Subject: `nginx container restart`
Content: `Container nginx was restarted`

**Comment by DL6ER** [comment]
![Screenshot from 2023-09-23 13-57-08](https://github.com/yubiuser/docker-event-monitor/assets/16748619/2d546b3c-6322-4708-aa8e-ce08df4601e0)

Just posting another example where a `docker compose` referencing would be very beneficial so I'd right away know which script is being affected here.

**Comment by yubiuser** [comment]
I see what you mean...
