### ISSUE TITLE
Be better at reporting container death

### ISSUE THREAD

**Issue by DL6ER** [yubiuser/docker-event-monitor#36]
One of my containers kept restarting because of a typo in its `docker-compose.yml` file. `docker-event-monitor` was very useful in figuring this out because my inbox kept filling:

![Screenshot from 2023-09-23 12-37-31](https://github.com/yubiuser/docker-event-monitor/assets/16748619/db0e26bd-704a-4d7c-99b3-bb4434f4cdbc)

The first one was
> Object 'Container' with ID 88085b96 from image containrrr/watchtower reported: stop

All following are:
> Object 'Container' with ID 2de67b6b from image containrrr/watchtower reported: start

`docker events` told me `container die` which was more helpful at pointing me into the right direction. Maybe `docker-event-monitor` can be improved in this way.

**Comment by yubiuser** [comment]
You are free to set the filters to whatever you like. The provided compose file is just an example, you should be able to use all filters from here: https://docs.docker.com/engine/reference/commandline/events/

Personally, I use

```yml
      FILTER: 'type=container,event=start,event=stop,event=kill,event=create,event=die'
```

But this seems a bit to much for everyone (e.g. watchtower updating an image and restarting the container will create 5 events). You are also not limited to `type=container`, you can e.g. use `network` or `image

**Comment by DL6ER** [comment]
Thanks, I will do this, I missed this in copy-pasting the compose file :-)

> e.g. watchtower updating an image and restarting the container will create 5 events

I stopped doing this very soon after it ruined my mail server consisting of a half a dozen coupled containers a few times. I set `watchtower` to `WATCHTOWER_MONITOR_ONLY: 'true'` so I get informed and restart manually once I have the time to potentially fix what might be happening.

**Comment by yubiuser** [comment]
> I set watchtower to WATCHTOWER_MONITOR_ONLY: 'true' 

Wise choice. I set it on per-container basis: non-essentials can be auto-upgradeable, but essential not.
